language: rust
rust: stable
cache: cargo
script:
    - cargo build --release --verbose
    #- cargo test --verbose
deploy:
    provider: releases
    api_key:
        secure: '7jH8lGCW1Twuzv6bbGSlPuCwuqN0lGKoOtJPTYONluIRzkX5dujoAcgKsJaVD1lF0Oe9I2aC+Bp5xU/ZJIlAcntxgR5A+1EuQuWWfwqgSTsthMYixnR7X369qnF4/O/KLbYS7/dlYB8hV6FFgkDJcBDopJ40Zqj3fDUHiofi5pmzTtlu+DAqpeEctjy0iqN8+ZHhXAavs5lGi602NmV4JePwBGM+v58IedCYlprE7613myIm050FbehpqHcddY1bVlO9MGIdU+MPVAW4WyAEEspd3nCHu69sjZ44+uoqopbaCQqlYYSJtOhU5v1P8icGGge9gYmxn+S2hfr61F+pNWnhEV/8yLSGbQ3+SRHwjbTpoogirgL9n6QgJ+AIpDgIcCcuUZ7OIy7DzpwMjYGxzKLTW03PNeNNWdyiPTJbVetl2Es9/SjsZ5LrC+XkKSXv+rQQGSS0tr518YtYYwIrNmtSC+ZQvJ50LMYh9wZ9UX8MmR9Mvhf80OG9pUvRqsKNJEGIeKhKihTPIbbLoBbg38h4od9horHUEdOuzoKBHmajbJIdPIwUPLzBLA0+bhIe428UTZXr4s+0KqSCPA8ILSA7F9wMptANJoGbpczNjlD3YCp547m64m6K/Evdk6s39H7b01UUI8znN9GWjcXgILPsZ3kCAMrEnpGb/yfDbdA='
    file: 'target/release/twitch-gift-farm'
    skip_cleanup: true
    on:
        tags: true
