language: rust
rust: stable
cache: cargo
script:
    - cargo build --release --verbose
    #- cargo test --verbose
deploy:
    provider: releases
    api_key:
        secure: 'x4jhm4LBT+Mt0rA6NR9WsrfP1EcAfVbKDHawd+lizwGixUtz/cxDoM6UfDlh9nkM/BjncLa0fvTSzabUsZFbfCvkmM8fX9C3+eWGaAN7ZWoR+RJ6wwDg966aTWF3AXMRr9YQzUfoPPLPPWHehvGekfTiRZZkhRH/viHEGouvDadS9IpEhuoJZyiZ6oYASLs8ExQLD7wbQ1wDDE1kvn4GOsMEQbwy2X9hIYegEinNFG44Zdn1qHoGbFOf32f8gqidXZDbvYhLHoXb7a2MUo6OfwGR6AS0jH/0gDMMFUKlzuP8RJCgdzGuDp/xSJeAbd8W4s/6N9wzI3bniFcanohZSTH6NBPA9xbjRmXbdR3pz6FOzm8r5C/tO5cfocHtvqpkY+kkRKtaJ0YM1aH1rpS7Anla16FyfHk7hIQf/2qDOAz8bqw4S/EIF8bOa+yNOxAPAlvjluHKY0DBE988K6nUBic8Yv+ahLQVx45T/NetIF5Lq4tXNYl3rypHwj8bcNbhP/1H5pKceViN/UfBbQzA5rxzEmrrGcXhDUg2sOTT66V64EmLljDtE9SHKPmBjzWvo2tzS9JI5JrI4/OrmWJQgAJssxALCR546F5PF/02Hv6qR8xIKm1/WFajIo2NaDsboxfqInM1Kh0eXb60UaekJ47WDG0q2vvhJi5IZiWK/BA='
    file: 'target/release/twitch-gift-farm'
    skip_cleanup: true
    on:
        tags: true
